# Generated by Django 2.2.2 on 2019-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
